//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.18 at 10:17:56 PM MEZ 
//


package de.fh_zwickau.bestand;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for buchType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="buchType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="titel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="autor" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="verlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="erscheinungsjahr" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="isbn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;element name="praesenzexemplar" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="ausleihe" type="{}ausleiheType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "buchType", propOrder = {
    "titel",
    "autor",
    "verlag",
    "erscheinungsjahr",
    "isbn",
    "praesenzexemplar",
    "ausleihe"
})
public class BuchType {

    @XmlElement(required = true)
    protected String titel;
    @XmlElement(required = true)
    protected List<String> autor;
    @XmlElement(required = true)
    protected String verlag;
    protected int erscheinungsjahr;
    @XmlElement(required = true)
    protected String isbn;
    protected String praesenzexemplar;
    protected AusleiheType ausleihe;

    /**
     * Gets the value of the titel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitel() {
        return titel;
    }

    /**
     * Sets the value of the titel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitel(String value) {
        this.titel = value;
    }

    /**
     * Gets the value of the autor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the autor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAutor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAutor() {
        if (autor == null) {
            autor = new ArrayList<String>();
        }
        return this.autor;
    }

    /**
     * Gets the value of the verlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerlag() {
        return verlag;
    }

    /**
     * Sets the value of the verlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerlag(String value) {
        this.verlag = value;
    }

    /**
     * Gets the value of the erscheinungsjahr property.
     * 
     */
    public int getErscheinungsjahr() {
        return erscheinungsjahr;
    }

    /**
     * Sets the value of the erscheinungsjahr property.
     * 
     */
    public void setErscheinungsjahr(int value) {
        this.erscheinungsjahr = value;
    }

    /**
     * Gets the value of the isbn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * Sets the value of the isbn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsbn(String value) {
        this.isbn = value;
    }

    /**
     * Gets the value of the praesenzexemplar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPraesenzexemplar() {
        return praesenzexemplar;
    }

    /**
     * Sets the value of the praesenzexemplar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPraesenzexemplar(String value) {
        this.praesenzexemplar = value;
    }

    /**
     * Gets the value of the ausleihe property.
     * 
     * @return
     *     possible object is
     *     {@link AusleiheType }
     *     
     */
    public AusleiheType getAusleihe() {
        return ausleihe;
    }

    /**
     * Sets the value of the ausleihe property.
     * 
     * @param value
     *     allowed object is
     *     {@link AusleiheType }
     *     
     */
    public void setAusleihe(AusleiheType value) {
        this.ausleihe = value;
    }

}
