//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.18 at 10:17:56 PM MEZ 
//


package de.fh_zwickau.bestand;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.fh_zwickau.bestand package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.fh_zwickau.bestand
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AusleiheType }
     * 
     */
    public AusleiheType createAusleiheType() {
        return new AusleiheType();
    }

    /**
     * Create an instance of {@link Bestand }
     * 
     */
    public Bestand createBestand() {
        return new Bestand();
    }

    /**
     * Create an instance of {@link BuchType }
     * 
     */
    public BuchType createBuchType() {
        return new BuchType();
    }

}
